### PR TITLE
Fix issues with thermal model handling

### PR DESCRIPTION
**Pull request by jzuhone**
This PR fixes a number of issues related to ACISpy's handling for thermal models.

* The call to `get_xija_model_spec` in the function `find_json` to get the model specification file originally set `check_version=True`, but this function was often called many times in a short interval in some applications and github did not appreciate the repeated requests. So this option is now turned off.
* The `find_json` function also had some convoluted logic to look for the JSON file in a different `chandra_models` repository path which has now been fixed.
* The `ThermalModelFromRun` class "divided" a string by a string instead of using the divide operator to concatenate a `Path` object and a string. This has now been fixed.
* The `ThermalModelRunner.from_backstop` had an error in computing the initial temperature from the start of a model run. This has now been fixed, and required an update to one of the test answers.
* A new `pytest` fixture has been added to allow one to store new answers when running the tests if necessary.
* The interface with `acis_thermal_check` has been updated to match the changes made in https://github.com/acisops/acis_thermal_check/pull/44.
* The planning limit for 1DEAMZT model was one degree lower than it should have been and this is fixed.

All regression tests pass with the answers fixed, and the new answers were hand-checked against the old. The new functionality to store answers has also been checked to ensure that the answers are identical if they are supposed to be the same.

### CODE REVIEW

**Comment by jzuhone** [comment]
@taldcroft does this need to go through the new control board process? it's not used for load review but it does get installed into skare.

**Comment by jzuhone** [comment]
@taldcroft just wanted to ask again if you thought this needed to go through FSDS (my supposition is not, but if you want to update it in skare you might have to?)

**Comment by taldcroft** [comment]
Sorry I missed the first comment @ mention. No, this does not need to go as a separate FSDS issue, but the assumption is that each PR that gets lumped into a Ska update (which goes to FSDS) has been reviewed internally, passes some sort of testing and does not break other stuff. We apply that to every Ska package update.

**Comment by jzuhone** [comment]
Ok--it's not necessary for this to go into the same ska update as acis_thermal_check if it's not convenient. It can wait until the next one.

**Pull request merged**
