### PR TITLE
Refactor and improve thermal model framework

### PR DESCRIPTION
**Pull request by jzuhone**
This somewhat large PR vastly improves and streamlines running thermal models in ACISpy. To summarize:

* Removes the helper methods for running a thermal model from the commanded states database (everything is in favor of kadi now)
* Refactors `SimulateECSRun` and `SimulateSingleState` so that they better represent their distinct functions
* Improved handling for non-ACIS thermal models
* Improved handling for running a thermal model using a backstop file by handling continuity
* Improved handling / error handling for getting model spec files; uses the `chandra_models` installed in SKA by default
* Improved error handling which a model is being run into the future (i.e., no telemetry)
* Tries to use f-strings in as many places as possible throughout the code
* Makes line thickness on plots 2 points, increases tick lengths slightly
* Significant improvements in documentation
* Added the beginnings of a ACISpy-wide test suite -- all major functionality in specific to thermal models is now tested

- [x] Functional testing (macOS).
- [x] Regression testing

### CODE REVIEW

**Comment by jzuhone** [comment]
@taldcroft so I don't know how you want to handle things like this. This is a pretty big update and it's really all code that only I've seen in detail. I did the functional testing and I'm hoping to add regression tests at some point in the near future. 

You can see the docs for the ACISpy thermal model stuff here (the version associated with this PR):

https://cxc.cfa.harvard.edu/acis/tmp/acispy_2.1.0/thermal_models.html

**Comment by taldcroft** [comment]
Basically when single-author code has big changes, we have to focus on functional testing and review. So the requirement here is to document your functional testing.

**Comment by jzuhone** [comment]
Hi @taldcroft, 

This is finished now.

Functional testing is largely accomplished due to the fact that the docs include Jupyter notebooks which are run with `nbsphinx` and turned into HTML pages, and these include nearly every feature in the package. I have checked the updates to the docs vs the stable version and everything looks correct. 

A docs build for this version is here:

https://cxc.cfa.harvard.edu/acis/tmp/acispy_2.1.0/

As I edited in the introduction above, I've also added unit and regression tests for the thermal model capability in ACISpy here, and in future PRs I'll be adding tests for the rest of the codebase.

**Comment by taldcroft** [comment]
@jzuhone - congrats on bringing this home, looks like a lot of improvements!

Is this a dependency for ACIS load reviews or in operations code? From FD process perspective that's the key thing that needs external review. Being honest I probably don't have the time to look into this much outside that role.

**Comment by jzuhone** [comment]
@taldcroft there's no *real* dependency, but we do use it for the following (so you may think that one of these falls under that definition):

1. it is used to generate the thermal models for this real-time page (plots at the bottom):

https://cxc.cfa.harvard.edu/acis/current_load_page/

but that's only as a cursory check to see how the models are doing in real-time--nothing we would rely on for making decisions in a real-time capacity. 

2. We use it to make dashboard plots. 

3. We also use it to plan long ECS runs.

**Comment by taldcroft** [comment]
Sounds good so you can merge whenever you want. We are aiming for a Ska flight release this week and could probably get it in if it is ready.

**Pull request merged**
